version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: postgres-container
    environment:
      POSTGRES_USER: lau
      POSTGRES_PASSWORD: lau2962003
      POSTGRES_DB: estate_elite
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  identity-service:
    build:
      context: ../src
      dockerfile: IdentityService.Dockerfile
    container_name: identity-service-container
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres
    networks:
      - backend_network

  nginx:
    build:
      context: ./nginx
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - identity-service
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
