version: "3.8"

services:
  db:
    image: postgres:17
    container_name: postgres_estate
    environment:
      POSTGRES_USER: lau
      POSTGRES_PASSWORD: lau2962003
      POSTGRES_DB: estate_elite
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  identity-service:
    build:
      context: ../src/Services/IdentityService
      dockerfile: Dockerfile
    container_name: identity-service
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"] # Thêm health check cho identity-service
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - identity-service

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
