version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: lau
      POSTGRES_PASSWORD: lau2962003
      POSTGRES_DB: estate_elite
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=lau
      - RABBITMQ_DEFAULT_PASS=lau2962003
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app_network
    restart: always

  identity-service-1:
    image: identity-service-image
    build:
      context: ../src
      dockerfile: identity-service.dockerfile
    container_name: identity-service-container-1
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgresConnection=Host=postgres-container;Port=5432;Database=estate_elite;Username=lau;Password=lau2962003
    depends_on:
      - postgres
    networks:
      - app_network

  identity-service-2:
    image: identity-service-image
    build:
      context: ../src
      dockerfile: identity-service.dockerfile
    container_name: identity-service-container-2
    ports:
      - "5002:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgresConnection=Host=postgres-container;Port=5432;Database=estate_elite;Username=lau;Password=lau2962003
    depends_on:
      - postgres
    networks:
      - app_network

  nginx:
    image: nginx-image
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - identity-service-1
      - identity-service-2
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data:
    driver: local
