import { Property } from './type';

export const sampleProperties: Property[] = [
  {
    id: '1',
    title: 'Căn hộ Vinhomes Central Park',
    address: '208 Nguyễn Hữu Cảnh, Bình Thạnh, TP.HCM',
    price: 3500000000,
    status: 'Đang bán',
    type: 'Căn hộ',
    area: 85,
    bedrooms: 2,
    bathrooms: 2,
    createdAt: '2025-03-15',
  },
  {
    id: '2',
    title: 'Nhà phố Thảo Điền',
    address: '12 Quốc Hương, Thảo Điền, Quận 2, TP.HCM',
    price: 12000000000,
    status: 'Đang cho thuê',
    type: 'Nhà phố',
    area: 200,
    bedrooms: 4,
    bathrooms: 3,
    createdAt: '2025-03-10',
  },
  {
    id: '3',
    title: 'Biệt thự Palm City',
    address: 'Palm City, Quận 9, TP.HCM',
    price: 18000000000,
    status: 'Đã bán',
    type: 'Biệt thự',
    area: 350,
    bedrooms: 5,
    bathrooms: 5,
    createdAt: '2025-02-28',
  },
  {
    id: '4',
    title: 'Đất nền Nhơn Trạch',
    address: 'Nhơn Trạch, Đồng Nai',
    price: 2500000000,
    status: 'Đang bán',
    type: 'Đất nền',
    area: 120,
    bedrooms: 0,
    bathrooms: 0,
    createdAt: '2025-02-15',
  },
  {
    id: '5',
    title: 'Căn hộ Masteri An Phú',
    address: 'An Phú, Quận 2, TP.HCM',
    price: 4200000000,
    status: 'Đã cho thuê',
    type: 'Căn hộ',
    area: 70,
    bedrooms: 2,
    bathrooms: 2,
    createdAt: '2025-01-22',
  },
];
